### ISSUE TITLE
HA mesh controller

### ISSUE THREAD

**Issue by noahjd** [traefik/mesh-helm-chart#12]
Hello,

Just a general question but is it possible to run multiple replicas of the mesh controller? I see the pdb is currently set to have 1 pod minimally available, but that is pretty strict because it holds up rolling updates of nodes and evictions of that pod. Thanks!

**Comment by kevinpollet** [comment]
Hello @noahjd and thanks for your interest in Traefik Mesh,

Currently, it is not possible to run multiple replicas of the mesh controller as each instance will compete to create the shadow service resources and the port mapping will not be shared by all controller instances. As you might guess, supporting HA requires more work on the controller side. For the pdb, feel free to open an issue on this specific subject.

One last thing, please use the [Traefik Mesh community forum](https://community.traefik.io/c/traefik-mesh/15) if you are more questions. We are trying to keep only issues and feature requests in the GitHub issue tracker.
